In [1]:
#definisi rumus normalisasi
def norm_feature(data):
    #data max
    n_max = max(data)
    #data min
    n_min = min(data)
    #panjang data
    l_data = len(data)

    #perulangan
    for i in range(0, l_data):
        #mencari normalisasi
        data[i] = (data[i] - n_min) / (n_max - n_min)

    return data

# rangkuman : 
# for i in '' = adalah perulangan
# len adalah panjang data. format = len('')
# for i in range(0,''): = perulangan dari 0 ke ''

In [2]:
data = [10, 25, 15, 30, 50]

n_data = norm_feature(data)
n_data

[0.0, 0.375, 0.125, 0.5, 1.0]

In [3]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [4]:
data = [
    [100, 0.01],
    [8, 0.05],
    [50, 0.005]
]
# dengan array, len(data) hanya bisa mengakses luaran array, dari 3x2 hasilnya menjadi 3 bukan 6.

# dengan numpy dapat dilihat panjang array sebenarnya.
np_data = np.asarray(data)
# mencari demensi array : np_data.shape
# hasilnya (3, 2)
mm_scaler = MinMaxScaler()
mm_data = mm_scaler.fit_transform(data) #harus array 2 demensi
mm_data


array([[1.        , 0.11111111],
       [0.        , 1.        ],
       [0.45652174, 0.        ]])

In [5]:
#bukan array
from statistics import mean, stdev
def std_feature(data):
    mean_data = mean(data)
    std_data = stdev(data)
    l_data = len(data)

    for i in range(0, l_data):
        data[i] = (data[i] - mean_data) / std_data
    return data

In [6]:
data_1 = [100, 0.001]
data = np.asarray(data_1)
std_data = std_feature(data_1)
std_data

[0.7071067811865476, -0.7071067811865476]

In [8]:
#dengan array dan len
from statistics import mean, stdev
def std_feature(data):
    baris_data = len(data)
    kolom_data = len(data[0])

    for i in range(0, baris_data):
        for j in range(0, kolom_data):
            data[i][j] = (data[i][j] - mean(data[j])) / stdev(data[j])
    return data

In [9]:
data = [
    [100, 0.001],
    [8, 0.05],
    [50, 0.005],
    [88, 0.07],
    [4, 0.1]
]
data = np.asarray(data)
std_data = std_feature(data)
std_data

array([[ 0.70710678, -0.71582332],
       [ 7.95532544, -0.70710678],
       [49.69804328, -0.59084947],
       [87.46526419, -0.58023768],
       [ 3.97982851, -0.57533994]])

In [16]:
#dengan array dan shape
from statistics import mean, stdev, pstdev
def std_feature(data):
    baris_data = data.shape[0]
    kolom_data = data.shape[1]

    for i in range(0, baris_data):
        for j in range(0, kolom_data):
            #sample = stdev, populasi = pstdev
            data[i][j] = (data[i,j] - mean(data[:,j])) / stdev(data[:,j])
    return data

In [17]:
data = [
    [100, 0.001],
    [8, 0.05],
    [50, 0.005],
    [88, 0.07],
    [4, 0.1]
]
data = np.asarray(data)
std_data = std_feature(data)
std_data

array([[ 1.13053908, -1.04102352],
       [-0.58585228,  0.43340554],
       [ 0.54596936,  0.16378374],
       [ 1.78715622,  0.2189989 ],
       [ 1.53764773,  0.21485145]])

In [18]:
data = [
    [100, 0.001],
    [8, 0.05],
    [50, 0.005],
    [88, 0.07],
    [4, 0.1]
]
data = np.asarray(data)

In [19]:
#dengan function sklearn
from sklearn.preprocessing import StandardScaler
ss_scaler = StandardScaler()
std_data= ss_scaler.fit_transform(data)
std_data

array([[ 1.26398112, -1.16389967],
       [-1.06174414,  0.12639634],
       [ 0.        , -1.05856939],
       [ 0.96062565,  0.65304778],
       [-1.16286263,  1.44302493]])

In [20]:
#ordinal
from sklearn.preprocessing import OrdinalEncoder
oe = [
    ['POLINEMA'],
    ['PENS'],
    ['PNJ'],
    ['PNP'],
    ['POLBAN']
]
ord_oe = OrdinalEncoder().fit_transform(oe)
ord_oe

array([[4.],
       [0.],
       [1.],
       [2.],
       [3.]])

In [21]:
#one-hot
from sklearn.preprocessing import OneHotEncoder
oe = [
    ['POLINEMA'],
    ['PENS'],
    ['PNJ'],
    ['PNP'],
    ['POLBAN']
]
ohe_oe = OneHotEncoder().fit_transform(oe)
ohe_oe.toarray()


array([[0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [22]:
#Contoh studi kasus TF-IDF: 
corpus = [
    'the house had a tiny little mouse',
    'the cat saw the mouse',
    'the mouse ran away from the house',
    'the cat finally ate the mouse',
    'the end of the mouse story'
]

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(stop_words='english')
response = vectorizer.fit_transform(corpus)
#print(response.toarray())
#print(response)
a = vectorizer.get_feature_names()
b = response.todense()
print(a, b)

['ate', 'away', 'cat', 'end', 'finally', 'house', 'little', 'mouse', 'ran', 'saw', 'story', 'tiny'] [[0.         0.         0.         0.         0.         0.4755751
  0.58946308 0.28088232 0.         0.         0.         0.58946308]
 [0.         0.         0.58873218 0.         0.         0.
  0.         0.34771471 0.         0.72971837 0.         0.        ]
 [0.         0.58946308 0.         0.         0.         0.4755751
  0.         0.28088232 0.58946308 0.         0.         0.        ]
 [0.58946308 0.         0.4755751  0.         0.58946308 0.
  0.         0.28088232 0.         0.         0.         0.        ]
 [0.         0.         0.         0.67009179 0.         0.
  0.         0.31930233 0.         0.         0.67009179 0.        ]]


In [34]:
#tambahan materi split
sentence = 'the house had a tiny little mouse. the cat saw the mouse. the mouse ran away from the house.'
stc_split = sentence.split('.')
stc_split

['the house had a tiny little mouse',
 ' the cat saw the mouse',
 ' the mouse ran away from the house',
 '']

In [ ]:
# TUGAS 1
f = open('.txt','r')
stc = f.read()
stc