PEMBAHASAN MATERI

In [1]:
#definisi rumus normalisasi
def norm_feature(data):
    #data max
    n_max = max(data)
    #data min
    n_min = min(data)
    #panjang data
    l_data = len(data)

    #perulangan
    for i in range(0, l_data):
        #mencari normalisasi
        data[i] = (data[i] - n_min) / (n_max - n_min)

    return data

# rangkuman : 
# for i in '' = adalah perulangan
# len adalah panjang data. format = len('')
# for i in range(0,''): = perulangan dari 0 ke ''

In [2]:
data = [10, 25, 15, 30, 50]

n_data = norm_feature(data)
n_data

[0.0, 0.375, 0.125, 0.5, 1.0]

In [3]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [4]:
data = [
    [100, 0.01],
    [8, 0.05],
    [50, 0.005]
]
# dengan array, len(data) hanya bisa mengakses luaran array, dari 3x2 hasilnya menjadi 3 bukan 6.

# dengan numpy dapat dilihat panjang array sebenarnya.
np_data = np.asarray(data)
# mencari demensi array : np_data.shape
# hasilnya (3, 2)
mm_scaler = MinMaxScaler()
mm_data = mm_scaler.fit_transform(data) #harus array 2 demensi
mm_data


array([[1.        , 0.11111111],
       [0.        , 1.        ],
       [0.45652174, 0.        ]])

In [5]:
#bukan array
from statistics import mean, stdev
def std_feature(data):
    mean_data = mean(data)
    std_data = stdev(data)
    l_data = len(data)

    for i in range(0, l_data):
        data[i] = (data[i] - mean_data) / std_data
    return data

In [6]:
data_1 = [100, 0.001]
data = np.asarray(data_1)
std_data = std_feature(data_1)
std_data

[0.7071067811865476, -0.7071067811865476]

In [8]:
#dengan array dan len
from statistics import mean, stdev
def std_feature(data):
    baris_data = len(data)
    kolom_data = len(data[0])

    for i in range(0, baris_data):
        for j in range(0, kolom_data):
            data[i][j] = (data[i][j] - mean(data[j])) / stdev(data[j])
    return data

In [9]:
data = [
    [100, 0.001],
    [8, 0.05],
    [50, 0.005],
    [88, 0.07],
    [4, 0.1]
]
data = np.asarray(data)
std_data = std_feature(data)
std_data

array([[ 0.70710678, -0.71582332],
       [ 7.95532544, -0.70710678],
       [49.69804328, -0.59084947],
       [87.46526419, -0.58023768],
       [ 3.97982851, -0.57533994]])

In [16]:
#dengan array dan shape
from statistics import mean, stdev, pstdev
def std_feature(data):
    baris_data = data.shape[0]
    kolom_data = data.shape[1]

    for i in range(0, baris_data):
        for j in range(0, kolom_data):
            #sample = stdev, populasi = pstdev
            data[i][j] = (data[i,j] - mean(data[:,j])) / stdev(data[:,j])
    return data

In [17]:
data = [
    [100, 0.001],
    [8, 0.05],
    [50, 0.005],
    [88, 0.07],
    [4, 0.1]
]
data = np.asarray(data)
std_data = std_feature(data)
std_data

array([[ 1.13053908, -1.04102352],
       [-0.58585228,  0.43340554],
       [ 0.54596936,  0.16378374],
       [ 1.78715622,  0.2189989 ],
       [ 1.53764773,  0.21485145]])

In [18]:
data = [
    [100, 0.001],
    [8, 0.05],
    [50, 0.005],
    [88, 0.07],
    [4, 0.1]
]
data = np.asarray(data)

In [19]:
#dengan function sklearn
from sklearn.preprocessing import StandardScaler
ss_scaler = StandardScaler()
std_data= ss_scaler.fit_transform(data)
std_data

array([[ 1.26398112, -1.16389967],
       [-1.06174414,  0.12639634],
       [ 0.        , -1.05856939],
       [ 0.96062565,  0.65304778],
       [-1.16286263,  1.44302493]])

In [20]:
#ordinal
from sklearn.preprocessing import OrdinalEncoder
oe = [
    ['POLINEMA'],
    ['PENS'],
    ['PNJ'],
    ['PNP'],
    ['POLBAN']
]
ord_oe = OrdinalEncoder().fit_transform(oe)
ord_oe

array([[4.],
       [0.],
       [1.],
       [2.],
       [3.]])

In [21]:
#one-hot
from sklearn.preprocessing import OneHotEncoder
oe = [
    ['POLINEMA'],
    ['PENS'],
    ['PNJ'],
    ['PNP'],
    ['POLBAN']
]
ohe_oe = OneHotEncoder().fit_transform(oe)
ohe_oe.toarray()


array([[0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [22]:
#Contoh studi kasus TF-IDF: 
corpus = [
    'the house had a tiny little mouse',
    'the cat saw the mouse',
    'the mouse ran away from the house',
    'the cat finally ate the mouse',
    'the end of the mouse story'
]

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(stop_words='english')
response = vectorizer.fit_transform(corpus)
#print(response.toarray())
#print(response)
a = vectorizer.get_feature_names()
b = response.todense()
print(a, b)

['ate', 'away', 'cat', 'end', 'finally', 'house', 'little', 'mouse', 'ran', 'saw', 'story', 'tiny'] [[0.         0.         0.         0.         0.         0.4755751
  0.58946308 0.28088232 0.         0.         0.         0.58946308]
 [0.         0.         0.58873218 0.         0.         0.
  0.         0.34771471 0.         0.72971837 0.         0.        ]
 [0.         0.58946308 0.         0.         0.         0.4755751
  0.         0.28088232 0.58946308 0.         0.         0.        ]
 [0.58946308 0.         0.4755751  0.         0.58946308 0.
  0.         0.28088232 0.         0.         0.         0.        ]
 [0.         0.         0.         0.67009179 0.         0.
  0.         0.31930233 0.         0.         0.67009179 0.        ]]


In [34]:
#tambahan materi split
sentence = 'the house had a tiny little mouse. the cat saw the mouse. the mouse ran away from the house.'
stc_split = sentence.split('.')
stc_split

['the house had a tiny little mouse',
 ' the cat saw the mouse',
 ' the mouse ran away from the house',
 '']

In [ ]:
# f = open('.txt','r')
# stc = f.read()
# stc

TUGAS JOBSHEET 1

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

In [3]:
text = open('orange.txt', 'r')
corpus = text.read()

TF-IDF per kata

In [4]:
import re
lowertext = corpus.lower()
# remove special characters and digits
rschar = re.sub("(\\d|\\W)+"," ",lowertext)

In [5]:
words = rschar.split(' ')
words

['',
 'earth',
 's',
 'dreamlands',
 'a',
 'bbs',
 'for',
 'text',
 'file',
 'junkies',
 'rpgnet',
 'gm',
 'file',
 'archive',
 'site',
 'the',
 'five',
 'orange',
 'pips',
 'when',
 'i',
 'glance',
 'over',
 'my',
 'notes',
 'and',
 'records',
 'of',
 'the',
 'sherlock',
 'holmes',
 'cases',
 'between',
 'the',
 'years',
 'and',
 'i',
 'am',
 'faced',
 'by',
 'so',
 'many',
 'which',
 'present',
 'strange',
 'and',
 'interesting',
 'features',
 'that',
 'it',
 'is',
 'no',
 'easy',
 'matter',
 'to',
 'know',
 'which',
 'to',
 'choose',
 'and',
 'which',
 'to',
 'leave',
 'some',
 'however',
 'have',
 'already',
 'gained',
 'publicity',
 'through',
 'the',
 'papers',
 'and',
 'others',
 'have',
 'not',
 'offered',
 'a',
 'field',
 'for',
 'those',
 'peculiar',
 'qualities',
 'which',
 'my',
 'friend',
 'possessed',
 'in',
 'so',
 'high',
 'a',
 'degree',
 'and',
 'which',
 'it',
 'is',
 'the',
 'object',
 'of',
 'these',
 'papers',
 'to',
 'illustrate',
 'some',
 'too',
 'have',
 'baff

In [6]:
vectorizer = TfidfVectorizer(stop_words='english')
vectors = vectorizer.fit_transform(words)
feature_names = vectorizer.get_feature_names()
dense = vectors.todense()
denselist = dense.tolist()
df = pd.DataFrame(denselist, columns = feature_names)
df

abjure  able  abound  absence  absolute  abuse  accident  accidental  \
0        0.0   0.0     0.0      0.0       0.0    0.0       0.0         0.0   
1        0.0   0.0     0.0      0.0       0.0    0.0       0.0         0.0   
2        0.0   0.0     0.0      0.0       0.0    0.0       0.0         0.0   
3        0.0   0.0     0.0      0.0       0.0    0.0       0.0         0.0   
4        0.0   0.0     0.0      0.0       0.0    0.0       0.0         0.0   
...      ...   ...     ...      ...       ...    ...       ...         ...   
7427     0.0   0.0     0.0      0.0       0.0    0.0       0.0         0.0   
7428     0.0   0.0     0.0      0.0       0.0    0.0       0.0         0.0   
7429     0.0   0.0     0.0      0.0       0.0    0.0       0.0         0.0   
7430     0.0   0.0     0.0      0.0       0.0    0.0       0.0         0.0   
7431     0.0   0.0     0.0      0.0       0.0    0.0       0.0         0.0   

      accidents  accomplishment  ...  wrong  wrongfully  wrote  year  years  \
0           0.0             0.0  ...    0.0         0.0    0.0   0.0    0.0   
1           0.0             0.0  ...    0.0         0.0    0.0   0.0    0.0   
2           0.0             0.0  ...    0.0         0.0    0.0   0.0    0.0   
3           0.0             0.0  ...    0.0         0.0    0.0   0.0    0.0   
4           0.0             0.0  ...    0.0         0.0    0.0   0.0    0.0   
...         ...             ...  ...    ...         ...    ...   ...    ...   
7427        0.0             0.0  ...    0.0         0.0    0.0   0.0    0.0   
7428        0.0             0.0  ...    0.0         0.0    0.0   0.0    0.0   
7429        0.0             0.0  ...    0.0         0.0    0.0   0.0    0.0   
7430        0.0             0.0  ...    0.0         0.0    0.0   0.0    0.0   
7431        0.0             0.0  ...    0.0         0.0    0.0   0.0    0.0   

      yes  yesterday  young  youngster  zero  
0     0.0        0.0    0.0        0.0   0.0  
1     0.0        0.0    0.0        0.0   0.0  
2     0.0        0.0    0.0        0.0   0.0  
3     0.0        0.0    0.0        0.0   0.0  
4     0.0        0.0    0.0        0.0   0.0  
...   ...        ...    ...        ...   ...  
7427  0.0        0.0    0.0        0.0   0.0  
7428  0.0        0.0    0.0        0.0   0.0  
7429  0.0        0.0    0.0        0.0   0.0  
7430  0.0        0.0    0.0        0.0   0.0  
7431  0.0        0.0    0.0        0.0   0.0  

[7432 rows x 1572 columns]

In [7]:
# loc digunakan untuk mengakses data berdasarkan label (nama kolom).
df.loc[0:2, 'earth']

0    0.0
1    1.0
2    0.0
Name: earth, dtype: float64

In [8]:
# iloc digunakan untuk mengakses data berdasarkan posisi.
df.iloc[0:2, 380:400]

driving  drove  drunken  dry  dundee  duty  dweller  early  earth  ease  \
0      0.0    0.0      0.0  0.0     0.0   0.0      0.0    0.0    0.0   0.0   
1      0.0    0.0      0.0  0.0     0.0   0.0      0.0    0.0    1.0   0.0   

   easily  east  easterly  eastern  easy  eccentric  eccentricity  edge  \
0     0.0   0.0       0.0      0.0   0.0        0.0           0.0   0.0   
1     0.0   0.0       0.0      0.0   0.0        0.0           0.0   0.0   

   edged  education  
0    0.0        0.0  
1    0.0        0.0

In [9]:
# describe() digunakan untuk menampilkan deskriptif statistik data. Hanya kolom yang bertipe numerik yang akan ditampilkan statistiknya.
df.describe()

abjure         able       abound      absence     absolute  \
count  7432.000000  7432.000000  7432.000000  7432.000000  7432.000000   
mean      0.000135     0.000942     0.000135     0.000135     0.000135   
std       0.011600     0.030678     0.011600     0.011600     0.011600   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       0.000000     0.000000     0.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

             abuse     accident   accidental    accidents  accomplishment  \
count  7432.000000  7432.000000  7432.000000  7432.000000     7432.000000   
mean      0.000135     0.000135     0.000135     0.000135        0.000135   
std       0.011600     0.011600     0.011600     0.011600        0.011600   
min       0.000000     0.000000     0.000000     0.000000        0.000000   
25%       0.000000     0.000000     0.000000     0.000000        0.000000   
50%       0.000000     0.000000     0.000000     0.000000        0.000000   
75%       0.000000     0.000000     0.000000     0.000000        0.000000   
max       1.000000     1.000000     1.000000     1.000000        1.000000   

       ...        wrong   wrongfully        wrote         year        years  \
count  ...  7432.000000  7432.000000  7432.000000  7432.000000  7432.000000   
mean   ...     0.000135     0.000135     0.000135     0.000673     0.000807   
std    ...     0.011600     0.011600     0.011600     0.025931     0.028404   
min    ...     0.000000     0.000000     0.000000     0.000000     0.000000   
25%    ...     0.000000     0.000000     0.000000     0.000000     0.000000   
50%    ...     0.000000     0.000000     0.000000     0.000000     0.000000   
75%    ...     0.000000     0.000000     0.000000     0.000000     0.000000   
max    ...     1.000000     1.000000     1.000000     1.000000     1.000000   

               yes    yesterday        young    youngster         zero  
count  7432.000000  7432.000000  7432.000000  7432.000000  7432.000000  
mean      0.000538     0.000135     0.001346     0.000135     0.000135  
std       0.023195     0.011600     0.036659     0.011600     0.011600  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 1572 columns]

TF-IDF per Splitline

In [30]:
import string
# remove number, whitespace, tandabaca
cleaning = re.sub(r'\d+', '', lowertext)
cleaning = cleaning.strip()
cleaning = cleaning.translate(str.maketrans("","",string.punctuation))
docs = cleaning.splitlines()
docs


['',
 '         earths dreamlands',
 '             ',
 '              a bbs for text file junkies',
 '              rpgnet gm file archive site',
 '',
 '',
 '                the five orange pips',
 '',
 '  when i glance over my notes and records of the sherlock',
 'holmes cases between the years  and  i am faced by so',
 'many which present strange and interesting features that it is no',
 'easy matter to know which to choose and which to leave some',
 'however have already gained publicity through the papers and',
 'others have not offered a field for those peculiar qualities which',
 'my friend possessed in so high a degree and which it is the',
 'object of these papers to illustrate some too have baffled his',
 'analytical skill and would be as narratives beginnings without',
 'an ending while others have been but partially cleared up and',
 'have their explanations founded rather upon conjecture and sur',
 'mise than on that absolute logical proof which was so dear to',
 'him there

In [33]:
vectorizer = TfidfVectorizer(stop_words='english')
vectors = vectorizer.fit_transform(docs)
print(vectors)
feature_names = vectorizer.get_feature_names()
dense = vectors.todense()
denselist = dense.tolist()
df = pd.DataFrame(denselist, columns = feature_names)
df

  (1, 375)	0.7071067811865476
  (1, 387)	0.7071067811865476
  (3, 708)	0.5148701198938749
  (3, 495)	0.4846738693600748
  (3, 1387)	0.4846738693600748
  (3, 90)	0.5148701198938749
  (4, 1249)	0.45239407812828164
  (4, 52)	0.45239407812828164
  (4, 574)	0.45239407812828164
  (4, 1161)	0.45239407812828164
  (4, 495)	0.4258619404194846
  (7, 980)	0.6796907627108469
  (7, 919)	0.7334987846517178
  (9, 1225)	0.41631804973527764
  (9, 1098)	0.4647644212410564
  (9, 891)	0.5525727618210478
  (9, 567)	0.5525727618210478
  (10, 465)	0.5897072304563806
  (10, 1567)	0.4828491904776284
  (10, 180)	0.5305832373354841
  (10, 634)	0.37092245801671464
  (11, 485)	0.5111869333771284
  (11, 692)	0.5430350062477396
  (11, 1330)	0.47106310677764013
  (11, 1027)	0.47106310677764013
  :	:
  (731, 1566)	0.40253928561616015
  (732, 1176)	0.4618143446356029
  (732, 1308)	0.43590435540225986
  (732, 789)	0.43590435540225986
  (732, 883)	0.5011503877659387
  (732, 791)	0.3943990185250447
  (733, 617)	0.551795654

abjure  able  abound  absence  absolute  abuse  accident  accidental  \
0       0.0   0.0     0.0      0.0       0.0    0.0       0.0         0.0   
1       0.0   0.0     0.0      0.0       0.0    0.0       0.0         0.0   
2       0.0   0.0     0.0      0.0       0.0    0.0       0.0         0.0   
3       0.0   0.0     0.0      0.0       0.0    0.0       0.0         0.0   
4       0.0   0.0     0.0      0.0       0.0    0.0       0.0         0.0   
..      ...   ...     ...      ...       ...    ...       ...         ...   
734     0.0   0.0     0.0      0.0       0.0    0.0       0.0         0.0   
735     0.0   0.0     0.0      0.0       0.0    0.0       0.0         0.0   
736     0.0   0.0     0.0      0.0       0.0    0.0       0.0         0.0   
737     0.0   0.0     0.0      0.0       0.0    0.0       0.0         0.0   
738     0.0   0.0     0.0      0.0       0.0    0.0       0.0         0.0   

     accidents  accomplishment  ...  wrong  wrongfully  wrote  year  years  \
0          0.0             0.0  ...    0.0         0.0    0.0   0.0    0.0   
1          0.0             0.0  ...    0.0         0.0    0.0   0.0    0.0   
2          0.0             0.0  ...    0.0         0.0    0.0   0.0    0.0   
3          0.0             0.0  ...    0.0         0.0    0.0   0.0    0.0   
4          0.0             0.0  ...    0.0         0.0    0.0   0.0    0.0   
..         ...             ...  ...    ...         ...    ...   ...    ...   
734        0.0             0.0  ...    0.0         0.0    0.0   0.0    0.0   
735        0.0             0.0  ...    0.0         0.0    0.0   0.0    0.0   
736        0.0             0.0  ...    0.0         0.0    0.0   0.0    0.0   
737        0.0             0.0  ...    0.0         0.0    0.0   0.0    0.0   
738        0.0             0.0  ...    0.0         0.0    0.0   0.0    0.0   

     yes  yesterday  young  youngster  zero  
0    0.0        0.0    0.0        0.0   0.0  
1    0.0        0.0    0.0        0.0   0.0  
2    0.0        0.0    0.0        0.0   0.0  
3    0.0        0.0    0.0        0.0   0.0  
4    0.0        0.0    0.0        0.0   0.0  
..   ...        ...    ...        ...   ...  
734  0.0        0.0    0.0        0.0   0.0  
735  0.0        0.0    0.0        0.0   0.0  
736  0.0        0.0    0.0        0.0   0.0  
737  0.0        0.0    0.0        0.0   0.0  
738  0.0        0.0    0.0        0.0   0.0  

[739 rows x 1573 columns]